---
- name: Preparación de Nodos SecDevOps
  hosts: wazuh, podman
  become: yes
  gather_facts: yes

  tasks:
    - name: Actualizar el sistema (Apt upgrade)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Instalar herramientas esenciales
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - net-tools
        state: present

    - name: Verificar estado de la memoria RAM
      ansible.builtin.shell: free -h
      register: ram_status

    - name: Mostrar RAM (Para confirmar los 4GB asignados)
      ansible.builtin.debug:
        var: ram_status.stdout_lines
