---
- name: Hardening de servicios (CIS Benchmark)
  hosts: all
  become: yes

  tasks:
    - name: Recolectar información sobre los servicios del sistema
      ansible.builtin.service_facts:

    - name: Asegurar que existe /run/sshd para la validación de Ansible
      ansible.builtin.file:
        path: /run/sshd
        state: directory
        mode: '0755'

    - name: Aplicar configuraciones seguras en sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '(?i)^#?{{ item.key }}\b'
        line: '{{ item.key }} {{ item.value }}'
        state: present
        validate: /usr/sbin/sshd -t -f %s
      loop:
        - { key: 'UsePAM', value: 'yes' }
        - { key: 'PermitUserEnvironment', value: 'no' }
        - { key: 'PermitEmptyPasswords', value: 'no' }
        - { key: 'MaxSessions', value: '2' }
        - { key: 'LogLevel', value: 'VERBOSE' }
        - { key: 'IgnoreRhosts', value: 'yes' }
        - { key: 'HostbasedAuthentication', value: 'no' }
        - { key: 'GSSAPIAuthentication', value: 'no' }
        - { key: 'MACs', value: '-hmac-md5,hmac-md5-96,hmac-ripemd160,umac-64@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com' }
      notify: Reiniciar SSH


# ----------------- Hardening de red (SYSCTL) ------------ #

    - name: Configurar parámetros de red seguros (sysctl)
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.all.secure_redirects', value: '0' }
        - { key: 'net.ipv4.conf.default.secure_redirects', value: '0' }
        - { key: 'net.ipv4.conf.default.secure_redirects', value: '1' }

# ----------------- DESACTIVACION MÓDULOS DEL KERNEL ------------ #

    - name: Blacklist de sistemas de archivos innecesarios
      ansible.builtin.copy:
        dest: "/etc/modprobe.d/cis_blacklist.conf"
        content: |
          install cramfs /bin/false
          install freevxfs /bin/false
          install jffs2 /bin/false
          install hfs /bin/false
          install hfsplus /bin/false
          install udf /bin/false


  handlers:
    - name: Reiniciar SSH
      ansible.builtin.systemd:
        name: ssh
        state: restarted
    
    - name: Recargar systemd y reiniciar agente
      ansible.builtin.systemd:
        daemon_reload: yes
        name: wazuh-agent
        state: restarted
