---
- name: Despliegue de WAF perimetral para Capa de Aplicacion
  hosts: podman
  become: yes

  tasks:
    - name: Configurar UFW para permitir tráfico del WAF y la DVWA
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '80'
        - '8080'
      notify: Recargar Firewall

    - name: Configurar Carpeta de Reglas (Solo Lectura para el WAF)
      ansible.builtin.file:
        path: /etc/waf/rules
        state: directory
        owner: root
        group: "101"
        mode: '0750'

    - name: Configurar Carpeta de Logs (Escritura para el WAF)
      ansible.builtin.file:
        path: /var/log/waf
        state: directory
        owner: "101"
        group: root
        mode: '0750'

    - name: Crear archivo de unidad Quadlet para el WAF
      ansible.builtin.copy:
        dest: /etc/containers/systemd/waf.container
        content: |
          [Unit]
          Description=Contenedor WAF (Nginx + ModSecurity)
          After=dvwa.service
          
          [Container]
          Image=docker.io/owasp/modsecurity-crs:nginx
          PublishPort=80:8080
          Environment=BACKEND=http://10.0.0.20:8080
          Volume=/var/log/waf:/var/log/nginx:Z
          Volume=/var/log/waf:/var/log/nginx:Z

          [Install]
          WantedBy=multi-user.target

    - name: Monitorización del WAF
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: "</ossec_config>"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK WAF -->"
        block: |
          <localfile>
            <log_format>apache</log_format>
            <location>/var/log/waf/error.log</location>
          </localfile>
      notify: Reiniciar Agente

  handlers:
    - name: Reiniciar servicios
      ansible.builtin.systemd:
        daemon_reload: yes
        name: "{{ item }}"
        state: restarted
      loop:
        - dvwa.service
        - waf.service

    - name: Reiniciar Agente
      ansible.builtin.systemd:
        name: wazuh-agent
        state: restarted

    - name: Recargar Firewall
      community.general.ufw:
        state: reloaded
