---
- name: Despliegue Maestro Nodo Podman + Agente Wazuh
  hosts: podman
  become: yes

  tasks:
    - name: Instalar Podman y motor de contenedores
      ansible.builtin.apt:
        name: [podman, gnupg2, curl]
        state: latest
        update_cache: yes

    - name: Configurar Repositorio y Agente Wazuh
      block:

        - name: Añadir llave GPG
          ansible.builtin.shell: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg"
          args:
            creates: /usr/share/keyrings/wazuh.gpg

        - name: Añadir repo
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"

        - name: Instalar agente
          ansible.builtin.apt:
            name: wazuh-agent
            state: latest
            update_cache: yes

    - name: Vincular Agente al Manager (10.0.0.10)
      ansible.builtin.lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>MANAGER_IP</address>'
        line: "      <address>10.0.0.10</address>"
      notify: Reiniciar Agente

    - name: Habilitar y arrancar el servicio del agente
      systemd:
        name: wazuh-agent
        enabled: yes
        state: started
#-------------------------------------------------------------------------------------------
    - name: Habilitar persistencia de procesos para el usuario walter
      ansible.builtin.command: loginctl enable-linger walter
      args:
        creates: "/var/lib/systemd/linger/walter"


    - name: Crear directorios de datos en el Home de walter
      ansible.builtin.file:
        path: "/home/walter/{{ item }}"
        state: directory
        owner: walter
        group: walter
        mode: '0755'
      loop:
        - "dvwa/logs"
        - "dvwa/mysql"
        - ".config/containers/systemd"

    - name: Desplegar Quadlet en el contexto de usuario
      ansible.builtin.copy:
        dest: "/home/walter/.config/containers/systemd/dvwa.container"
        owner: walter
        group: walter
        content: |
          [Container]
          Image=docker.io/vulnerables/web-dvwa:latest
          PublishPort=8080:80
          Volume=/home/walter/dvwa/logs:/var/log/apache2:Z
          Volume=/home/walter/dvwa/mysql:/var/lib/mysql:Z

          [Install]
          WantedBy=default.target


    - name: Iniciar servicio DVWA en modo usuario
      ansible.builtin.systemd:
        name: dvwa
        scope: user
        state: started
        enabled: yes
        daemon_reload: yes
      become: yes
      become_user: walter

#------------------------------------------------------------------------------------------


    - name: Monitorización de la DVWA
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: "</ossec_config>"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK DVWA -->"
        block: |
          <localfile>
            <log_format>apache</log_format>
            <location>/home/walter/dvwa/logs/access.log</location>
          </localfile>
      notify: Reiniciar Agente

  handlers:
    - name: Reiniciar Agente
      ansible.builtin.systemd:
        name: wazuh-agent
        state: restarted
