---


- name: Migración Integral a Rootless - WAF + DVWA + Wazuh Agent
  hosts: podman
  become: yes

  vars:
    user_name: walter
    user_home: "/home/{{ user_name }}"
    waf_port: 8081
    dvwa_port: 8082

  tasks:

    - name: Instalar Podman y motor de contenedores
      ansible.builtin.apt:
        name: [podman, gnupg2, curl]
        state: latest
        update_cache: yes

    - name: Configurar Repositorio y Agente Wazuh
      block:

        - name: Añadir llave GPG
          ansible.builtin.shell: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg"
          args:
            creates: /usr/share/keyrings/wazuh.gpg

        - name: Añadir repo
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"

        - name: Instalar agente
          ansible.builtin.apt:
            name: wazuh-agent
            state: latest
            update_cache: yes

    - name: Vincular Agente al Manager (10.0.0.10)
      ansible.builtin.lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>MANAGER_IP</address>'
        line: "      <address>10.0.0.10</address>"
      notify: Reiniciar Agente

    - name: Habilitar y arrancar el servicio del agente
      systemd:
        name: wazuh-agent
        enabled: yes
        state: started

#---------------------------------------------------------------------------------------------------------------
    - name: Persistencia de procesos para el usuario (Linger)
      ansible.builtin.command: "loginctl enable-linger {{ user_name }}"
      args:
        creates: "/var/lib/systemd/linger/{{ user_name }}"

    - name: Crear estructura de directorios en el Home de walter
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
      loop:
        - "{{ user_home }}/dvwa/logs"
        - "{{ user_home }}/dvwa/mysql"
        - "{{ user_home }}/waf/logs"
        - "{{ user_home }}/waf/conf"
        - "{{ user_home }}/.config/containers/systemd"


    - name: Configuración de Nginx para el WAF (Proxy al 8082)
      ansible.builtin.copy:
        dest: "{{ user_home }}/waf/conf/default.conf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        content: |
          server {
              listen {{ waf_port }};
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:{{ dvwa_port }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
    - name: Configurar VirtualHost de Apache para registrar la IP real
      ansible.builtin.copy:
        dest: "{{ user_home }}/dvwa/000-default.conf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html
              ErrorLog ${APACHE_LOG_DIR}/error.log
              LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" proxy
              CustomLog ${APACHE_LOG_DIR}/access.log proxy
          </VirtualHost>

    - name: Crear Quadlet para DVWA
      ansible.builtin.copy:
        dest: "{{ user_home }}/.config/containers/systemd/dvwa.container"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        content: |
          [Unit]
          Description=Contenedor DVWA Rootless

          [Container]
          Image=docker.io/vulnerables/web-dvwa:latest
          PublishPort={{ dvwa_port }}:80
          Volume={{ user_home }}/dvwa/logs:/var/log/apache2:Z
          Volume=dvwa_db_data:/var/lib/mysql
          #Volume={{ user_home }}/dvwa/realip.conf:/etc/apache2/conf-enabled/realip.conf:Z
          Volume={{ user_home }}/dvwa/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:Z
          [Install]
          WantedBy=default.target


    - name: Crear Quadlet para WAF
      ansible.builtin.copy:
        dest: "{{ user_home }}/.config/containers/systemd/waf.container"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        content: |
          [Unit]
          After=dvwa.service

          [Container]
          Image=docker.io/owasp/modsecurity-crs:nginx
          Volume={{ user_home }}/waf/conf/default.conf:/etc/nginx/templates/conf.d/default.conf.template:Z
          Volume={{ user_home }}/waf/logs:/var/log/nginx:Z,U
          Network=host

          [Install]
          WantedBy=default.target
    
    - name: Despertar el motor systemd del usuario (necesario en máquinas nuevas)
      ansible.builtin.command: "systemctl start user@1000.service"

    - name: Iniciar servicios Quadlet en modo usuario
      ansible.builtin.systemd:
        name: "{{ item }}"
        scope: user
        state: restarted
        daemon_reload: yes
      become: yes
      become_user: "{{ user_name }}"
      environment:
        XDG_RUNTIME_DIR: "/run/user/1000"
      loop:
        - dvwa
        - waf

    - name: Configurar Wazuh para leer logs Rootless
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: "</ossec_config>"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK WAF -->"
        block: |
          <localfile>
            <log_format>apache</log_format>
            <location>{{ user_home }}/waf/logs/access.log</location>
          </localfile>
          <localfile>
            <log_format>apache</log_format>
            <location>{{ user_home }}/waf/logs/error.log</location>
          </localfile>
      notify: Reiniciar Agente

    - name: Crear directorio de override para el agente de Wazuh
      ansible.builtin.file:
        path: /etc/systemd/system/wazuh-agent.service.d
        state: directory
        mode: '0755'

    - name: Configurar dependencia Servicio Ssh levantado en el Agente
      ansible.builtin.copy:
        dest: /etc/systemd/system/wazuh-agent.service.d/override.conf
        content: |
          [Unit]
          After=ssh.service
          Wants=ssh.service

          [Service]
          ExecStartPre=/bin/sleep 5
      notify: Reiniciar Agente

  handlers:
    - name: Reiniciar Agente
      ansible.builtin.service:
        name: wazuh-agent
        state: restarted
