---
- name: Preparar entorno de ataque Red Team
  hosts: redteam
  become: yes

  tasks:
    - name: Actualizar repositorios base
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Instalar arsenal de Pentesting y utilidades de rendimiento
      ansible.builtin.apt:
        name:
          - nmap       # Escaneo de puertos y evasión de firewalls
          - sqlmap     # Inyecciones SQL automatizadas
          - hydra      # Fuerza bruta paralela
          - tmux       # Multiplexor de terminal
          - htop       # Monitorización de recursos
          - curl
          - wget
          - python3
          - python3-pip
          - python3-bs4
          - python3-requests
          - git
        state: present

    - name: Crear directorio para scripts del RedTeam
      ansible.builtin.file:
        path: /home/walter/scripts
        state: directory
        owner: walter
        group: walter
        mode: '0700'

    - name: Optimizar OS para ataques de alta concurrencia (File Descriptors)
      ansible.builtin.blockinfile:
        path: /etc/security/limits.conf
        block: |
          * soft nofile 65535
          * hard nofile 65535
          root soft nofile 65535
          root hard nofile 65535
      notify: Aplicar sysctl


# ===========================================================================
#  INTEGRACIÓN DE CUPP (Generador de Diccionarios personalizados)
# ===========================================================================

    - name: Clonar repositorio oficial de CUPP
      ansible.builtin.git:
        repo: 'https://github.com/Mebus/cupp.git'
        dest: /opt/cupp
        depth: 1

    - name: Configurar permisos de ejecución para el script de Python
      ansible.builtin.file:
        path: /opt/cupp/cupp.py
        mode: '0755'

    - name: Crear enlace simbólico para acceso global a CUPP
      ansible.builtin.file:
        src: /opt/cupp/cupp.py
        dest: /usr/local/bin/cupp
        state: link


# ===========================================================================
#  SCRIPTS PERSONALIZADOS
# ===========================================================================

    - name: Mover scripts y diccionario
      ansible.builtin.copy:
        src: /home/walter/proyectos/tfc/SecDevOps/scripts/redteam/
        dest: /home/walter/scripts
        owner: walter
        group: walter
        mode: '0700'

  handlers:
    - name: Aplicar sysctl
      ansible.builtin.command: sysctl -p
