---
- name: Despliegue Maestro Wazuh Manager
  hosts: wazuh
  become: yes

  tasks:
    - name: Actualizar caché de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Descargar instalador de Wazuh
      ansible.builtin.shell: |
        curl -sL -f -A "Mozilla/5.0" -o /root/wazuh-install.sh https://packages.wazuh.com/4.14/wazuh-install.sh
      args:
        creates: /root/wazuh-install.sh

    - name: Ejecutar instalador/actualizador Wazuh
      ansible.builtin.shell: "bash /root/wazuh-install.sh -a"
      args:
        chdir: /root
        creates: /var/ossec/etc/ossec.conf

    - name: Extraer, mover y limpiar credenciales de Wazuh
      block:
        - name: Extraer txt de contraseñas
          ansible.builtin.shell: "tar -axf /root/wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O > /root/passwords.txt"
        - name: Descargar a Anfitrión
          ansible.builtin.fetch:
            src: /root/passwords.txt
            dest: "/home/walter/v2_secdevops/credenciales_wazuh.txt"
            flat: yes
        - name: Eliminar rastro de contraseñas en MV (Hardening)
          ansible.builtin.file:
            path: /root/passwords.txt
            state: absent

    - name: Configurar receptor Syslog para OPNsense
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: '</ossec_config>'
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (SYSLOG) -->"
        block: |
          <remote>
            <connection>syslog</connection>
            <port>514</port>
            <protocol>udp</protocol>
            <allowed-ips>10.0.0.254</allowed-ips>
          </remote>
      notify: Reiniciar Wazuh Manager

    - name: Configurar decodificadores para Suricata (OPNsense)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/decoders/local_decoder.xml
        marker: "<!-- {mark} Decodificadores Wazuh // Ansible -->"
        block: |
          <decoder name="suricata">
            <program_name>^suricata</program_name>
          </decoder>

          <decoder name="suricata-json">
            <parent>suricata</parent>
            <plugin_decoder>JSON_Decoder</plugin_decoder>
          </decoder>
          
          <decoder name="dvwa-rootless">
            <parent>systemd</parent>
            <regex>(\d+.\d+.\d+.\d+)</regex>
            <order>srcip</order>
          </decoder>

      notify: Reiniciar Wazuh Manager

    - name: Desplegar reglas personalizadas (SQLi, Brute Force y Suricata)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/rules/local_rules.xml
        owner: root
        group: wazuh
        mode: '0660'
        marker: "<!-- {mark} Reglas Wazuh // Ansible -->"
        block: |
          <group name="secdevops_rules,">
            <rule id="100005" level="0">
              <decoded_as>suricata</decoded_as>
              <description>[RED] Suricata: Logs de OPNsense procesados correctamente.</description>
            </rule>

            <rule id="100006" level="5">
              <if_sid>100005</if_sid>
              <field name="event_type">^alert$</field>
              <description>[RED] Suricata: Alerta detectada - $(alert.signature)</description>
            </rule>

            <rule id="100007" level="12">
              <if_sid>100006</if_sid>
              <field name="alert.severity">^1$</field>
              <description>[RED] Suricata: Alerta CRÍTICA - $(alert.signature)</description>
            </rule>

            <rule id="100008" level="5">
              <if_sid>100006</if_sid>
              <match>403 Forbidden</match>
              <description>[RED] Suricata: Confirmado bloqueo del WAF (403 Detectado)</description>
            </rule>

            <rule id="100011" level="12">
              <if_sid>31333</if_sid>
              <match>SQL Injection Attack Detected</match>
              <description>[WAF] ModSecurity: Intento de Inyección SQL detenido</description>
            </rule>

            <rule id="100012" level="10">
              <if_sid>31333</if_sid>
              <match>sqlmap</match>
              <description>[WAF] ModSecurity: Escaneo de vulnerabilidades detectado</description>
            </rule>

            <rule id="100020" level="0">
              <program_name>systemd-dvwa</program_name>
              <description>[WEB] Logs del servicio DVWA.</description>
            </rule>

            <rule id="100021" level="1">
              <if_sid>100020</if_sid>
              <regex type="pcre2">POST\s+/login\.php.*302</regex>
              <description>[WEB] Intento de login en DVWA desde $(srcip).</description>
            </rule>

            <rule id="100022" level="15" frequency="8" timeframe="60">
              <if_matched_sid>100021</if_matched_sid>
              <same_source_ip />
              <description>[WEB] Ataque de FUERZA BRUTA detectado desde la IP $(srcip)</description>
              <mitre><id>T1110</id></mitre>
            </rule>

            <rule id="100030" level="3">
              <if_sid>5715</if_sid>
              <description>[HOST] Acceso SSH exitoso en el nodo $(hostname)</description>
            </rule>

            <rule id="100031" level="0">
              <if_sid>533, 530</if_sid>
              <regex>conmon|systemd-resolve|node</regex>
              <description>[HOST] Silenciados cambios de proceso internos.</description>
            </rule>

            <rule id="100013" level="0">
              <if_sid>31333</if_sid>
              <description>Silenciadas alertas genéricas de ModSecurity para evitar duplicados.</description>
            </rule>

            <rule id="651" level="10" overwrite="yes">
              <field name="parameters.program">firewall-drop</field>
              <field name="command">add</field>
              <description>[HOST] Respuesta Activa: Iniciando bloqueo de IP $(srcip) vía firewall-drop</description>
            </rule>

            <rule id="652" level="3" overwrite="yes">
              <field name="parameters.program">firewall-drop</field>
              <field name="command">delete</field>
              <description>[HOST] Respuesta Activa: IP $(srcip) desbloqueada vía firewall-drop</description>
            </rule>


          </group>

      notify: Reiniciar Wazuh Manager

    - name: Configurar Respuesta Activa en ossec.conf
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: "</ossec_config>"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (ACTIVE RESPONSE) -->"
        block: |
          <active-response>
            <command>firewall-drop</command>
            <location>local</location>
            <rules_id>100022</rules_id>
            <timeout>60</timeout>
          </active-response>
      notify: Reiniciar Wazuh Manager

  handlers:
    - name: Reiniciar Wazuh Manager
      ansible.builtin.systemd:
        name: wazuh-manager
        state: restarted
