---
- name: Despliegue Maestro Wazuh Manager
  hosts: wazuh
  become: yes

  tasks:
    - name: Actualizar caché de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Descargar instalador de Wazuh
      ansible.builtin.shell: |
        curl -sL -f -A "Mozilla/5.0" -o /root/wazuh-install.sh https://packages.wazuh.com/4.14/wazuh-install.sh
      args:
        creates: /root/wazuh-install.sh

    - name: Ejecutar instalador/actualizador Wazuh
      ansible.builtin.shell: "bash /root/wazuh-install.sh -a"
      args:
        chdir: /root
        creates: /var/ossec/etc/ossec.conf

    - name: Extraer, mover y limpiar credenciales de Wazuh
      block:
        - name: Extraer txt de contraseñas
          ansible.builtin.shell: "tar -axf /root/wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O > /root/passwords.txt"
        - name: Descargar a Anfitrión
          ansible.builtin.fetch:
            src: /root/passwords.txt
            dest: "/home/walter/v2_secdevops/credenciales_wazuh.txt"
            flat: yes
        - name: Eliminar rastro de contraseñas en MV (Hardening)
          ansible.builtin.file:
            path: /root/passwords.txt
            state: absent

    - name: Configurar receptor Syslog para OPNsense
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: '</ossec_config>'
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (SYSLOG) -->"
        block: |
          <remote>
            <connection>syslog</connection>
            <port>514</port>
            <protocol>udp</protocol>
            <allowed-ips>10.0.0.254</allowed-ips>
          </remote>
      notify: Reiniciar Wazuh Manager

    - name: Configurar decodificadores para Suricata (OPNsense)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/decoders/local_decoder.xml
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (DECODERS) -->"
        block: |
          <decoder name="suricata">
            <program_name>^suricata</program_name>
          </decoder>

          <decoder name="suricata-json">
            <parent>suricata</parent>
            <plugin_decoder>JSON_Decoder</plugin_decoder>
          </decoder>
      notify: Reiniciar Wazuh Manager

    - name: Desplegar reglas personalizadas (SQLi, Brute Force y Suricata)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/rules/local_rules.xml
        owner: root
        group: wazuh
        mode: '0660'
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (RULES) -->"
        block: |
          <group name="local,web_attacks,">
            <rule id="100021" level="3">
              <if_sid>31108, 31100</if_sid>
              <match>POST /login.php</match>
              <description>DVWA: Intento de autenticacion web detectado.</description>
            </rule>
            <rule id="100022" level="10" frequency="10" timeframe="60">
              <if_matched_sid>100021</if_matched_sid>
              <same_source_ip />
              <description>DVWA: Ataque de FUERZA BRUTA web detectado.</description>
              <mitre><id>T1110</id></mitre>
              <group>brute_force,web_attacks,</group>
            </rule>
            <rule id="100002" level="12">
              <if_sid>31100</if_sid>
              <regex type="pcre2">(?i)(%27|').*(or|and|union|select).*(=|\%3D)</regex>
              <description>¡Ataque SQLi detectado!</description>
              <mitre><id>T1213</id></mitre>
            </rule>
          </group>

          <group name="suricata,ids,">
            <rule id="100005" level="0">
              <decoded_as>suricata</decoded_as>
              <description>Logs de Suricata OPNsense procesados.</description>
            </rule>
            <rule id="100006" level="3">
              <if_sid>100005</if_sid>
              <field name="event_type">^alert$</field>
              <description>Suricata: Alerta detectada - $(alert.signature)</description>
              <group>ids,suricata,alert_exploit,</group>
            </rule>
            <rule id="100007" level="12">
              <if_matched_sid>100006</if_matched_sid>
              <field name="alert.severity">^1$</field>
              <description>Suricata: Alerta CRÍTICA detectada - $(alert.signature)</description>
              <group>ids,suricata,priority_1,</group>
            </rule>
          </group>
      notify: Reiniciar Wazuh Manager

    - name: Configurar Respuesta Activa en ossec.conf
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: "</ossec_config>"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (ACTIVE RESPONSE) -->"
        block: |
          <active-response>
            <command>firewall-drop</command>
            <location>local</location>
            <rules_id>100022</rules_id>
            <timeout>60</timeout>
          </active-response>
      notify: Reiniciar Wazuh Manager

  handlers:
    - name: Reiniciar Wazuh Manager
      ansible.builtin.systemd:
        name: wazuh-manager
        state: restarted
