---
- name: Despliegue Maestro Wazuh Manager
  hosts: wazuh
  become: yes

  vars:
    src_passw_vm: "/root/passwords.txt"
    dest_passw_anf: "{{ lookup('env', 'HOME') }}/proyectos/tfc/SecDevOps/ansible/credenciales_wazuh.txt"

  tasks:
    - name: Actualizar caché de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Descargar instalador de Wazuh
      ansible.builtin.shell: |
        curl -sL -f -A "Mozilla/5.0" -o /root/wazuh-install.sh https://packages.wazuh.com/4.14/wazuh-install.sh
      args:
        creates: /root/wazuh-install.sh

    - name: Ejecutar instalador/actualizador Wazuh
      ansible.builtin.shell: "bash /root/wazuh-install.sh -a"
      args:
        chdir: /root
        creates: /var/ossec/etc/ossec.conf

    - name: Extraer, mover y limpiar credenciales de Wazuh
      block:
        - name: Extraer txt de contraseñas
          ansible.builtin.shell: "tar -axf /root/wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O > {{ src_passw_vm }}"
        - name: Descargar a Anfitrión
          ansible.builtin.fetch:
            src: "{{ src_passw_vm }}"
            dest: "{{ dest_passw_anf }}"
            flat: yes
        - name: Eliminar rastro de contraseñas en MV (Hardening)
          ansible.builtin.file:
            path: "{{ src_passw_vm }}"
            state: absent

    - name: Configurar receptor Syslog para OPNsense
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: '</ossec_config>'
        marker: "<!-- {mark} Receptor Syslog del Firewall // Ansible -->"
        block: |
          <remote>
            <connection>syslog</connection>
            <port>514</port>
            <protocol>udp</protocol>
            <allowed-ips>10.0.0.254</allowed-ips>
          </remote>
      notify: Reiniciar Wazuh Manager
    
    - name: Configurar decodificadores para Suricata (OPNsense)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/decoders/local_decoder.xml
        owner: root
        group: wazuh
        mode: '0660'
        marker: "<!-- {mark} Decodificadores Wazuh // Ansible -->"
        block: "{{ lookup('file', 'files/local_decoder.xml') }}"

      notify: Reiniciar Wazuh Manager

    - name: Reglas Wazuh personalizadas
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/rules/local_rules.xml
        owner: root
        group: wazuh
        mode: '0660'
        marker: "<!-- {mark} Reglas Wazuh // Ansible -->"
        block: "{{ lookup('file', 'files/wazuh_local_rules.xml') }}"

      notify: Reiniciar Wazuh Manager

    - name: Configurar Respuesta Activa en ossec.conf
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertbefore: "</ossec_config>"
        marker: "<!-- {mark} Respuesta activa Wazuh // Ansible -->"
        block: |
          <active-response>
            <command>firewall-drop</command>
            <location>local</location>
            <rules_id>100202,100302</rules_id>
            <timeout>60</timeout>
          </active-response>
      notify: Reiniciar Wazuh Manager

  handlers:
    - name: Reiniciar Wazuh Manager
      ansible.builtin.systemd:
        name: wazuh-manager
        state: restarted
